version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app # 将当前目录挂载到容器的 /app 目录，方便开发时代码同步

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: